/* eslint-disable */
//prettier-ignore
module.exports = {
name: "@yarnpkg/plugin-engines",
factory: function (require) {
var plugin=(()=>{var _=Object.create,g=Object.defineProperty;var b=Object.getOwnPropertyDescriptor;var I=Object.getOwnPropertyNames,x=Object.getOwnPropertySymbols,j=Object.getPrototypeOf,P=Object.prototype.hasOwnProperty,L=Object.prototype.propertyIsEnumerable;var N=(r,e,n)=>e in r?g(r,e,{enumerable:!0,configurable:!0,writable:!0,value:n}):r[e]=n,u=(r,e)=>{for(var n in e||(e={}))P.call(e,n)&&N(r,n,e[n]);if(x)for(var n of x(e))L.call(e,n)&&N(r,n,e[n]);return r};var $=r=>g(r,"__esModule",{value:!0});var d=r=>{if(typeof require!="undefined")return require(r);throw new Error('Dynamic require of "'+r+'" is not supported')};var A=(r,e)=>{for(var n in e)g(r,n,{get:e[n],enumerable:!0})},G=(r,e,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let t of I(e))!P.call(r,t)&&t!=="default"&&g(r,t,{get:()=>e[t],enumerable:!(n=b(e,t))||n.enumerable});return r},m=r=>G($(g(r!=null?_(j(r)):{},"default",r&&r.__esModule&&"default"in r?{get:()=>r.default,enumerable:!0}:{value:r,enumerable:!0})),r);var q={};A(q,{default:()=>B});var s=m(d("@yarnpkg/core")),c;(function(n){n.Yarn="Yarn",n.Console="Console"})(c||(c={}));var a=class{constructor(e){this.throwWrongEngineError=(e,n,t,o)=>{let i=this.formatErrorMessage(e,n,t,o);this.throwError(i)};this.throwError=e=>{switch(this.errorReporter){case c.Yarn:this.reportYarnError(e);break;case c.Console:default:this.reportConsoleError(e);break}};this.reportYarnError=e=>{throw new s.ReportError(s.MessageName.UNNAMED,e)};this.reportConsoleError=e=>{console.error(e),process.exit(1)};this.formatErrorMessage=(e,n,t,o)=>{let{configuration:i}=this.project,E=s.formatUtils.applyStyle(i,s.formatUtils.pretty(i,this.engine,"green"),2),h=s.formatUtils.applyStyle(i,s.formatUtils.pretty(i,`[${t}]:`,"yellow"),2),p=s.formatUtils.applyStyle(i,s.formatUtils.pretty(i,`(${o})`,"yellow"),2),l=s.formatUtils.pretty(i,e,"cyan"),f=s.formatUtils.pretty(i,n,"cyan"),w=`
      ${h} The current ${E} version ${l} does not satisfy the required version ${f} ${p}.${["raw command","install"].includes(t)?`
      Note: Non-script commands can't be excluded through 'ignoreEngines'.`:""}
      `;return s.formatUtils.pretty(i,w,"red")};this.project=e.project,this.errorReporter=e.errorReporter}};var R=m(d("semver"));var y=class extends a{get engine(){return"Node"}verifyEngine(e,n,t){let o=e.node;o!=null&&((0,R.satisfies)(process.version,o,{includePrerelease:!0})||this.throwWrongEngineError(process.version.replace(/^v/i,""),o.replace(/^v/i,""),n,t))}};var S=m(d("semver")),v=m(d("@yarnpkg/core"));var k=class extends a{get engine(){return"Yarn"}verifyEngine(e,n,t){let o=e.yarn;o!=null&&((0,S.satisfies)(v.YarnVersion,o,{includePrerelease:!0})||this.throwWrongEngineError(v.YarnVersion,o,n,t))}};var C=(r,e,n,t)=>{var p,l;let o=r.getWorkspaceByCwd(r.cwd).manifest.raw,i=r.getWorkspaceByCwd(r.configuration.startingCwd).manifest.raw,E=(p=n?o.engines:u(u({},o.engines),i.engines))!=null?p:{},h=(l=i.ignoreEngines)!=null?l:[];if(n||!h.includes(t)){let f={project:r,errorReporter:e};[new y(f),new k(f)].forEach(Y=>Y.verifyEngine(E,n?"install":t,n?r.cwd:r.configuration.startingCwd))}},O=r=>e=>{process.env.PLUGIN_YARN_ENGINES_DISABLE==null&&C(e,r,!0)},T=r=>(e,n,t,o)=>process.env.PLUGIN_YARN_ENGINES_DISABLE!=null?e:async()=>(C(n,r,!1,o),e()),U=r=>(e,n)=>{process.env.PLUGIN_YARN_ENGINES_DISABLE==null&&n.npm_lifecycle_event==null&&C(e,r,!1,"raw command")},W={hooks:{validateProject:O(c.Yarn),wrapScriptExecution:T(c.Console),setupScriptEnvironment:U(c.Console)}},B=W;return q;})();
return plugin;
}
};
